 function Comp = addComponents2Panel_cine_LoadImage(hPanel)

h_Gap = 0.05; 
h_Button = 0.2;
% 
% nB = 2;
% h_Button = (1-h_Gap*(nB+2)-h_Info)/nB;
% 
BC_PB = [1 1 1]*0.25;

% load image
h = 1-h_Gap-h_Button;
Comp.Pushbutton.LoadImage = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Load Cine Series',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 h 0.6 h_Button], ...
                                'FontSize', 12, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_cine_Pushbutton_LoadImagePanel_LoadImage);
                        

% % image info
% h = 1-h_Gap-h_Info;
% Comp.hPanel.ImageInfo = uipanel('parent', hPanel,...
%                                 'Unit', 'Normalized',...
%                                 'Position', [.0, h, 1, h_Info], ...
%                                 'Title', '',...
%                                 'FontSize',                 10,...
%                                 'Units',                     'normalized', ...
%                                 'visible',                      'on', ...
%                                 'ForegroundColor',       'white',...
%                                 'BackgroundColor',       'black', ...
%                                 'HighlightColor',          'k',...
%                                 'ShadowColor',            'k');
% 
% nR = 3;
% txt.FirstRow = {'Name', 'Value'};
% txt.FirstColumn = {'FoV'; 'Image Size'; 'Pixel Size'};
% columnRatio = [1]; % width ratio to first column
% txt.DataStr = {'350'; ''; ''};
% FS = 10;
% 
% [Comp.hEdit.ImageInfo] = fun_myTable(Comp.hPanel.ImageInfo, nR, columnRatio, txt, FS);

    
