 function Comp = addComponents2Panel_Snake(hPanel)

 h_Gap = 0.02;
 h_Button = 0.15;
 w_Button = 0.7;
 x_Button = (1-w_Button)/2;
 
nG = 3;

w_Button2 = 0.45;
x_Button1 = 0.05;
x_Button2 = 0.5;

h = 1-h_Gap-h_Button;
Comp.Pushbutton.LoadSnake = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Load Snakes',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', 14, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Pushbutton_SnakePanel_LoadSnake);
                            
h = h-h_Gap*nG-h_Button;
Comp.Pushbutton.FreeHand = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Free Hand',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button1 h w_Button2 h_Button], ...
                                'FontSize', 14, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_SnakePanel_FreeHand);
                            
Comp.Togglebutton.Slither = uicontrol('parent', hPanel, ...
                                'Style', 'togglebutton',...
                                'String', 'Slither',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button2 h w_Button2 h_Button], ...
                                'FontSize', 14, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'g',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Togglebutton_SnakePanel_Slither);

h = h-h_Gap*nG-h_Button;
Comp.Togglebutton.ReDraw = uicontrol('parent', hPanel, ...
                                'Style', 'togglebutton',...
                                'String', 'reDraw',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button1 h w_Button2 h_Button], ...
                                'FontSize', 14, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Callback', @Callback_Togglebutton_SnakePanel_ReDraw);
                            
Comp.Pushbutton.Delete = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Delete',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button2 h w_Button2 h_Button], ...
                                'FontSize', 14, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_SnakePanel_DeleteSnake);
                          
 h = h-h_Gap*nG-h_Button;
Comp.Pushbutton.FreeHand = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Save Snakes',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', 14, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_SnakePanel_SaveSnake);
                           
                          