 function Comp = addComponents2Panel2_Button(hPanel)

 h_Gap = 0.05;
 h_Button = 0.4;
 w_Button = 0.8;
 x_Button = (1-w_Button)/2;

BC =  [1 1 1]*0.25;
FS = 11;
h = 1-h_Gap-h_Button;
% Comp.Radiobutton.Profile = uicontrol('parent', hPanel, ...
%                                 'Style', 'radiobutton',...
%                                 'String', 'Profile',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [x_Button h w_Button h_Button], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Radiobutton_ButtonPanel_Profile);
% h = h-h_Gap-h_Button;

Comp.Radiobutton.bwSum = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', 'bwSum',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Radiobutton_ButtonPanel_bwSum);

h = h-h_Gap-h_Button;
Comp.Radiobutton.Contour = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', 'Contour',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Radiobutton_ButtonPanel_Contour);

% h = h-h_Gap-h_Button;
% Comp.Radiobutton.Point = uicontrol('parent', hPanel, ...
%                                 'Style', 'radiobutton',...
%                                 'String', 'Point',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [x_Button h w_Button h_Button], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Radiobutton_ButtonPanel_Point);
