function Comp = addComponents2Panel2_Tumor(hPanel)

Comp.hAxis.Tumor = axes('Parent',                   hPanel, ...
                            'color',        'none',...
                            'xcolor', 'w',...
                            'ycolor', 'w', ...
                            'gridcolor',   'w',...
                            'Units',                    'normalized', ...
                            'HandleVisibility',     'callback', ...
                            'Position',                 [0.05 0.025 0.9 0.9]);

Comp.hAxis.Tumor.XAxisLocation='top';
hold(Comp.hAxis.Tumor, 'on')