 function Comp = addComponents2Panel_Snake(hPanel)

 h_Gap = 0.05;
 h_FreeHandPanel = 0.3;
 w_FreeHandPanel = 0.7;
 
Comp.Panel.FreeHand.hPanel = uipanel('Parent',                    hPanel,...    
                                'Title',                        '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [(1-w_FreeHandPanel)/2, 1-h_FreeHandPanel-h_Gap, w_FreeHandPanel, h_FreeHandPanel],...
                                    'visible',                      'on', ...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'k',...
                                'ShadowColor',            'black');
 
Comp.Panel.FreeHand.Pushbutton.FreeHand = uicontrol('parent', Comp.Panel.FreeHand.hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Free Hand',...
                                'Unit', 'Normalized',...
                                'Position', [0. 0.55 1. 0.45], ...
                                'FontSize', 14, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_SnakePanel_FreeHand);
                            
Comp.Panel.FreeHand.Togglebutton.Slither = uicontrol('parent', Comp.Panel.FreeHand.hPanel, ...
                                'Style', 'togglebutton',...
                                'String', 'Slither',...
                                'Unit', 'Normalized',...
                                'Position', [0. 0. 1. 0.45], ...
                                'FontSize', 14, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'g',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Togglebutton_SnakePanel_Slither);

                          
                            
                            
% % image info
% Comp.hPanel.ImageInfo = uipanel('parent', hPanel,...
%                                 'Unit', 'Normalized',...
%                                 'Position', [.0, .35, 1, .65], ...
%                                 'Title', '',...
%                                 'FontSize',                 11,...
%                                 'Units',                     'normalized', ...
%                                 'visible',                      'on', ...
%                                 'ForegroundColor',       'white',...
%                                 'BackgroundColor',       'black', ...
%                                 'HighlightColor',          'k',...
%                                 'ShadowColor',            'k');
% 
% nR = 3;
% txt.FirstRow = {'Name', 'Value'};
% txt.FirstColumn = {'FoV'; 'Image Size'; 'Pixel Size'};
% columnRatio = [1]; % width ratio to first column
% txt.DataStr = {'350'; ''; ''};
% 
% [Comp.hEdit.ImageInfo] = fun_myTable(Comp.hPanel.ImageInfo, nR, columnRatio, txt);
