 function Comp = addComponents2Panel_Snake(hPanel)

 h_Gap = 0.025;
 h_Table = 0.3;
 h_Button = 0.1;
 w_Button = 0.9;
 x_Button = (1-w_Button)/2;
 
nG = 3;

w_Button2 = 0.4;
x_Button1 = 0.05;
x_Button2 = 0.5;

FS = 11;
BC_PB = [1 1 1]*0.25;
BC_TB = [1 1 1]*0.75;


% slice No
h = 1-h_Gap-h_Table;
Comp.hPanel.SliceNo = uipanel('parent', hPanel,...
                                'Unit', 'Normalized',...
                                'Position', [.0, h, 1, h_Table], ...
                                'Title', '',...
                                'FontSize',                 10,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'k',...
                                'ShadowColor',            'k');

nR = 2;
txt.FirstRow = {'Name', 'Value'};
txt.FirstColumn = {'Start Slice'; 'End Slice'};
columnRatio = [1]; % width ratio to first column
txt.DataStr = {''; ''; ''};
FS = 10;

[Comp.hEdit.ImageInfo] = fun_myTable(Comp.hPanel.SliceNo, nR, columnRatio, txt, FS);

% button
h = h-h_Gap-h_Button;
Comp.Pushbutton.FreeHand = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Draw',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button1 h w_Button2 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Pushbutton_SnakePanel_FreeHand);
                            
Comp.Togglebutton.Slither = uicontrol('parent', hPanel, ...
                                'Style', 'togglebutton',...
                                'String', 'Slither',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button2 h w_Button2 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_TB,...
                                'ForegroundColor', 'g',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Togglebutton_SnakePanel_Slither);

h = h-h_Gap*4-h_Button;
Comp.Togglebutton.ReDraw = uicontrol('parent', hPanel, ...
                                'Style', 'togglebutton',...
                                'String', 'reDraw',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button1 h w_Button2 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_TB,...
                                'ForegroundColor', 'g',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Togglebutton_SnakePanel_ReDraw);
                            
Comp.Pushbutton.Delete = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Delete',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button2 h w_Button2 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Pushbutton_SnakePanel_DeleteSnake);
                          
 h = h-h_Gap*5-h_Button;
Comp.Pushbutton.SaveSnake = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Save Snakes (Points)',...
                                'Unit', 'Normalized',...
                                'Position', [0.05 h 0.9 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Pushbutton_SnakePanel_SaveSnake);
                           
                          