function View = addPointFig(hFig)
            
View.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 0, 1, 1], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');
                            
View.hAxis.PlotPoint = axes('Parent',     View.hPanel, ...
                                'color',        'none',...
                                'xcolor', 'w',...
                                'ycolor', 'w', ...
                                'gridcolor',   'w',...
                                'Units',                    'normalized', ...
                                'HandleVisibility',     'callback', ...
                                'Position',                 [0.05 0.025 0.9 0.9]);

View.hAxis.PlotPoint.XAxisLocation='top';
hold(View.hAxis.PlotPoint, 'on')
    
View.hPlotObj.PlotPoint.All = line(View.hAxis.PlotPoint, 'XData', [], 'YData', [],  'Marker', '.',  'MarkerSize', 12, 'Color', 'c', 'LineStyle', '-');
View.hPlotObj.PlotPoint.Current = line(View.hAxis.PlotPoint, 'XData', [], 'YData', [],  'Marker', '.',  'MarkerSize', 16, 'Color', 'r', 'LineStyle', 'none');
